development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: opsworks_rails_demo_dev

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: opsworks_rails_demo_test

production: &production
  adapter: mysql2
  host: localhost
  database: opsworks_rails_demo
  username: opsworks_demo
  password: 7DD2xwSJfeZRWcVt*fcpT6%#R
